"use client";

import { useCallback, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Sparkles } from "lucide-react";
import { useAppStore } from "@/store/app.store";
import { ProcessingIndicator } from "@/components/assistant/ProcessingIndicator";
import { suggestedQuestions } from "@/data/mock/conversation";
import type { SuggestedQuestion } from "@/services/types";
import { useTranslation } from "@/lib/i18n";
import { cn } from "@/lib/utils";
import { useChat } from "@/hooks/useChat";
import { resolveBilingual } from "@/lib/i18n";

export default function AskPage() {
  const router = useRouter();
  const { t } = useTranslation();
  const language = useAppStore((s) => s.language);
  const { analysis } = useAppStore();
  const { sendMessage, cancel, isStreaming } = useChat();

  useEffect(() => {
    return () => {
      cancel();
    };
  }, [cancel]);

  const handleAsk = useCallback(
    async (question: SuggestedQuestion) => {
      const text = resolveBilingual(question, language);
      await sendMessage(text);
      // If a report is associated with this question, navigate after streaming
      const reportId = mapQuestionToReport(question.id);
      if (reportId) {
        // Wait for streaming to finish, then navigate.
        // We watch the store's analysis.stage == "complete" via polling.
        const startedAt = Date.now();
        const timer = setInterval(() => {
          const stage = useAppStore.getState().analysis.stage;
          if (
            stage === "complete" ||
            Date.now() - startedAt > 30_000
          ) {
            clearInterval(timer);
            router.push(`/workspace/reports/${reportId}`);
          }
        }, 200);
      }
    },
    [sendMessage, language, router]
  );

  const isProcessing = (analysis.stage !== "idle" && analysis.stage !== "complete") || isStreaming;
  const isComplete = analysis.stage === "complete";

  return (
    <div className="min-h-full bg-background flex items-center justify-center p-6">
      <div className="w-full max-w-2xl">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-accent-soft mx-auto mb-4">
            <Sparkles className="h-8 w-8 text-accent" />
          </div>
          <h1 className={cn("text-3xl font-semibold text-foreground mb-2", language === "bn" && "lang-bn")}>
            {t("nav.askThalamus")}
          </h1>
          <p className={cn("text-foreground-muted", language === "bn" && "lang-bn")}>
            {t("askPage.subtitle")}
          </p>
        </div>

        {(isProcessing || isComplete) ? (
          <div className="max-w-md mx-auto">
            <ProcessingIndicator
              currentStage={analysis.stage}
              activeAgents={analysis.activeAgents}
            />
            {isComplete && (
              <p className={cn("text-center text-sm text-foreground-muted mt-4", language === "bn" && "lang-bn")}>
                {t("askPage.redirecting")}
              </p>
            )}
          </div>
        ) : (
          <div className="space-y-3">
            {suggestedQuestions.map((question) => {
              const text = resolveBilingual(question, language);
              return (
                <button
                  key={question.id}
                  onClick={() => handleAsk(question)}
                  className={cn(
                    "w-full glass rounded-xl p-5 text-left transition-colors",
                    "hover:bg-surface-elevated group"
                  )}
                >
                  <p className={cn("text-lg text-foreground group-hover:text-accent transition-colors", language === "bn" && "lang-bn")}>
                    {text}
                  </p>
                  <p className={cn("text-sm text-foreground-subtle mt-1", language === "bn" && "lang-bn")}>
                    {t("askPage.agentsWillAnalyze", { count: question.involvedAgents.length })}
                  </p>
                </button>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

// Local helper: map suggested-question ids to the static report route.
// (The streaming report generated by the orchestrator is a separate path.)
import { questionToReportMap } from "@/data/mock/conversation";
function mapQuestionToReport(id: string): string | undefined {
  return questionToReportMap[id];
}
